# Generated by Django 4.2.14 on 2024-08-10 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(verbose_name="Время выполнения"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency_number",
            field=models.PositiveIntegerField(verbose_name="Как часто"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency_unit",
            field=models.CharField(
                choices=[("minutes", "минуты"), ("hours", "часы"), ("days", "дни")],
                default="days",
                max_length=10,
                verbose_name="Интервалы времени",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(verbose_name="Признак приятной привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Признак публичности"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец привычки",
            ),
        ),
    ]
